// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";
import {
  Icon
} from "../chunks/chunk-IXDMRUES.js";
import "../chunks/chunk-BVM6H744.js";

// virtual:button/social-icon
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Button-Social-Icon-Yj4a.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, getFonts, getPropertyControls, Link, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var enabledGestures = { kQqCu1Lo4: { hover: true } };
var serializationHash = "framer-Ts8ES";
var variantClassNames = { kQqCu1Lo4: "framer-v-1rngdfz" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0 ? void 0 : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = { Bold: "bold", Duotone: "duotone", Fill: "fill", Light: "light", Regular: "regular", Thin: "thin" };
var getProps = ({ background, height, hover, icon, iconColor, iconWeight, id, link, newTab, width, ...props }) => {
  var _ref, _ref1, _ref2, _humanReadableEnumMap_iconWeight, _ref3, _ref4, _ref5, _ref6;
  return { ...props, GIA1PYRq4: link !== null && link !== void 0 ? link : props.GIA1PYRq4, JTiufUbD3: (_ref = hover !== null && hover !== void 0 ? hover : props.JTiufUbD3) !== null && _ref !== void 0 ? _ref : "var(--token-2b6a96af-8d2f-4024-85fc-877d4ce5bb0f, rgb(23, 25, 27))", Q0e1fj3zT: (_ref1 = background !== null && background !== void 0 ? background : props.Q0e1fj3zT) !== null && _ref1 !== void 0 ? _ref1 : "var(--token-2b6a96af-8d2f-4024-85fc-877d4ce5bb0f, rgb(23, 25, 27))", RbsbqGimB: (_ref2 = icon !== null && icon !== void 0 ? icon : props.RbsbqGimB) !== null && _ref2 !== void 0 ? _ref2 : "XLogo", u_PTlUbwt: (_ref4 = (_ref3 = (_humanReadableEnumMap_iconWeight = humanReadableEnumMap[iconWeight]) !== null && _humanReadableEnumMap_iconWeight !== void 0 ? _humanReadableEnumMap_iconWeight : iconWeight) !== null && _ref3 !== void 0 ? _ref3 : props.u_PTlUbwt) !== null && _ref4 !== void 0 ? _ref4 : "fill", UmY9H7zg_: (_ref5 = newTab !== null && newTab !== void 0 ? newTab : props.UmY9H7zg_) !== null && _ref5 !== void 0 ? _ref5 : true, wYxLdx7tO: (_ref6 = iconColor !== null && iconColor !== void 0 ? iconColor : props.wYxLdx7tO) !== null && _ref6 !== void 0 ? _ref6 : "var(--token-c40dec17-ad9b-478b-a7f0-e25384b15814, rgb(255, 255, 255))" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, GIA1PYRq4, UmY9H7zg_, RbsbqGimB, wYxLdx7tO, u_PTlUbwt, Q0e1fj3zT, JTiufUbD3, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "kQqCu1Lo4", enabledGestures, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(Link, { href: GIA1PYRq4, nodeId: "kQqCu1Lo4", openInNewTab: UmY9H7zg_, children: /* @__PURE__ */ _jsx(motion.a, { ...restProps, ...gestureHandlers, "aria-label": "Link", className: `${cx(serializationHash, ...sharedStyleClassNames, "framer-1rngdfz", className, classNames)} framer-k59o3t`, "data-framer-name": "Social Button", layoutDependency, layoutId: "kQqCu1Lo4", ref: ref !== null && ref !== void 0 ? ref : ref1, style: { backgroundColor: Q0e1fj3zT, borderBottomLeftRadius: 12, borderBottomRightRadius: 12, borderTopLeftRadius: 12, borderTopRightRadius: 12, ...style }, variants: { "kQqCu1Lo4-hover": { backgroundColor: JTiufUbD3 } }, ...addPropertyOverrides({ "kQqCu1Lo4-hover": { "data-framer-name": void 0 } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(ComponentViewportProvider, { children: /* @__PURE__ */ _jsx(motion.div, { className: "framer-13x6bo1-container", layoutDependency, layoutId: "tXK9mMKyX-container", children: /* @__PURE__ */ _jsx(Icon, { color: wYxLdx7tO, height: "100%", iconSearch: "House", iconSelection: RbsbqGimB, id: "tXK9mMKyX", layoutId: "tXK9mMKyX", mirrored: false, selectByList: true, style: { height: "100%", width: "100%" }, weight: u_PTlUbwt, width: "100%" }) }) }) }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Ts8ES.framer-k59o3t, .framer-Ts8ES .framer-k59o3t { display: block; }", ".framer-Ts8ES.framer-1rngdfz { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 44px; }", ".framer-Ts8ES .framer-13x6bo1-container { flex: none; height: 25px; position: relative; width: 25px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Ts8ES.framer-1rngdfz { gap: 0px; } .framer-Ts8ES.framer-1rngdfz > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Ts8ES.framer-1rngdfz > :first-child { margin-left: 0px; } .framer-Ts8ES.framer-1rngdfz > :last-child { margin-right: 0px; } }", ".framer-Ts8ES.framer-v-1rngdfz.hover.framer-1rngdfz { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 44px); }"];
var FramerQRJQnv7DX = withCSS(Component, css, "framer-Ts8ES");
var stdin_default = FramerQRJQnv7DX;
FramerQRJQnv7DX.displayName = "Button/Social Icon";
FramerQRJQnv7DX.defaultProps = { height: 44, width: 44 };
addPropertyControls(FramerQRJQnv7DX, { GIA1PYRq4: { title: "Link", type: ControlType.Link }, UmY9H7zg_: { defaultValue: true, title: "New Tab", type: ControlType.Boolean }, RbsbqGimB: (PhosphorControls === null || PhosphorControls === void 0 ? void 0 : PhosphorControls["iconSelection"]) && { ...PhosphorControls["iconSelection"], defaultValue: "XLogo", description: void 0, hidden: void 0, title: "Icon" }, wYxLdx7tO: { defaultValue: 'var(--token-c40dec17-ad9b-478b-a7f0-e25384b15814, rgb(255, 255, 255)) /* {"name":"Absolute White"} */', title: "Icon Color", type: ControlType.Color }, u_PTlUbwt: (PhosphorControls === null || PhosphorControls === void 0 ? void 0 : PhosphorControls["weight"]) && { ...PhosphorControls["weight"], defaultValue: "fill", description: void 0, hidden: void 0, title: "Icon Weight" }, Q0e1fj3zT: { defaultValue: 'var(--token-2b6a96af-8d2f-4024-85fc-877d4ce5bb0f, rgb(23, 25, 27)) /* {"name":"10"} */', title: "Background", type: ControlType.Color }, JTiufUbD3: { defaultValue: 'var(--token-2b6a96af-8d2f-4024-85fc-877d4ce5bb0f, rgb(23, 25, 27)) /* {"name":"10"} */', title: "Hover", type: ControlType.Color } });
addFonts(FramerQRJQnv7DX, [{ explicitInter: true, fonts: [] }, ...PhosphorFonts], { supportsExplicitInterCodegen: true });

// virtual:button/social-icon
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
