// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";

// virtual:button/toggle
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Button-Toggle-cScd.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["s7cL3CSyf", "q9iKDLWOI"];
var serializationHash = "framer-nF7iI";
var variantClassNames = { q9iKDLWOI: "framer-v-lmw1kk", s7cL3CSyf: "framer-v-1famao6" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { OFF: "q9iKDLWOI", ON: "s7cL3CSyf" };
var getProps = ({ click, height, id, width, ...props }) => {
  return { ...props, kgfVBtQOq: click ?? props.kgfVBtQOq, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "s7cL3CSyf" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, kgfVBtQOq, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "s7cL3CSyf", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTap16qua3n = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (kgfVBtQOq) {
      const res = await kgfVBtQOq(...args);
      if (res === false) return false;
    }
    setVariant("q9iKDLWOI");
  });
  const onTapruplaw = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (kgfVBtQOq) {
      const res = await kgfVBtQOq(...args);
      if (res === false) return false;
    }
  });
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-1famao6", className, classNames), "data-framer-name": "ON", "data-highlight": true, layoutDependency, layoutId: "s7cL3CSyf", onTap: onTap16qua3n, ref: refBinding, style: { backgroundColor: "rgb(101, 0, 180)", borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, ...style }, variants: { q9iKDLWOI: { backgroundColor: "var(--token-ed3b63a2-509e-4d49-8b32-4225b3c51ff5, rgb(95, 99, 108))" } }, ...addPropertyOverrides({ q9iKDLWOI: { "data-framer-name": "OFF", onTap: onTapruplaw } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(motion.div, { className: "framer-1d3y1hv", "data-framer-name": "Shape", layoutDependency, layoutId: "GmK8YOKAP", style: { backgroundColor: "rgb(255, 255, 255)", borderBottomLeftRadius: 100, borderBottomRightRadius: 100, borderTopLeftRadius: 100, borderTopRightRadius: 100, boxShadow: "0px 2px 2px 0px rgba(0, 0, 0, 0.3)" } }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-nF7iI.framer-sapsw9, .framer-nF7iI .framer-sapsw9 { display: block; }", ".framer-nF7iI.framer-1famao6 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 4px; position: relative; width: 37px; }", ".framer-nF7iI .framer-1d3y1hv { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 12px); position: relative; width: 12px; }", ".framer-nF7iI.framer-v-lmw1kk.framer-1famao6 { justify-content: flex-start; }"];
var FramerFlkPOfZJu = withCSS(Component, css, "framer-nF7iI");
var stdin_default = FramerFlkPOfZJu;
FramerFlkPOfZJu.displayName = "Button/Toggle";
FramerFlkPOfZJu.defaultProps = { height: 20, width: 37 };
addPropertyControls(FramerFlkPOfZJu, { variant: { options: ["s7cL3CSyf", "q9iKDLWOI"], optionTitles: ["ON", "OFF"], title: "Variant", type: ControlType.Enum }, kgfVBtQOq: { title: "Click", type: ControlType.EventHandler } });
addFonts(FramerFlkPOfZJu, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:button/toggle
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "q9iKDLWOI"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
