// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";

// virtual:helper/clients-logo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Helper-Clients-Logo-UGzp.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var serializationHash = "framer-EsZJE";
var variantClassNames = { RMTMJ4BMT: "framer-v-1lfdte7" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var toResponsiveImage = (value) => {
  if (typeof value === "object" && value !== null && typeof value.src === "string") {
    return value;
  }
  return typeof value === "string" ? { src: value } : void 0;
};
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, logo, width, ...props }) => {
  var _ref;
  return { ...props, RjHY3scMX: (_ref = logo !== null && logo !== void 0 ? logo : props.RjHY3scMX) !== null && _ref !== void 0 ? _ref : { src: "https://framerusercontent.com/images/lTJrvV1xsPd6oXWXa8c9etY9U.svg" } };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, RjHY3scMX, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "RMTMJ4BMT", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-1lfdte7", className, classNames), "data-framer-name": "Clients Logo", layoutDependency, layoutId: "RMTMJ4BMT", ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, children: /* @__PURE__ */ _jsx(Image, { background: { alt: "", fit: "fit", loading: getLoadingLazyAtYPosition(((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + (0 + (((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 42) - 0 - (((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 42) - 0) * 1) / 2)), pixelHeight: 42, pixelWidth: 126, sizes: `max(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"}, 1px)`, ...toResponsiveImage(RjHY3scMX), ...{ positionX: "center", positionY: "center" } }, className: "framer-11ggfdo", "data-framer-name": "Logo", layoutDependency, layoutId: "m4m15PdqB" }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-EsZJE.framer-1irh35h, .framer-EsZJE .framer-1irh35h { display: block; }", ".framer-EsZJE.framer-1lfdte7 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 42px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 126px; }", ".framer-EsZJE .framer-11ggfdo { flex: 1 0 0px; height: 100%; overflow: hidden; position: relative; width: 1px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-EsZJE.framer-1lfdte7 { gap: 0px; } .framer-EsZJE.framer-1lfdte7 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-EsZJE.framer-1lfdte7 > :first-child { margin-left: 0px; } .framer-EsZJE.framer-1lfdte7 > :last-child { margin-right: 0px; } }"];
var Framernh0YWAI3s = withCSS(Component, css, "framer-EsZJE");
var stdin_default = Framernh0YWAI3s;
Framernh0YWAI3s.displayName = "Helper/Clients Logo";
Framernh0YWAI3s.defaultProps = { height: 42, width: 126 };
addPropertyControls(Framernh0YWAI3s, { RjHY3scMX: { __defaultAssetReference: "data:framer/asset-reference,lTJrvV1xsPd6oXWXa8c9etY9U.svg?originalFilename=Logo.svg&preferredSize=auto", title: "Logo", type: ControlType.ResponsiveImage } });
addFonts(Framernh0YWAI3s, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:helper/clients-logo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
