// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";

// virtual:helper/patch
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Helper-Patch-Yqjy.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getLoadingLazyAtYPosition, Image, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["yzW1wNmhu", "VeQSQ4PUT"];
var serializationHash = "framer-9SXsl";
var variantClassNames = { VeQSQ4PUT: "framer-v-159q512", yzW1wNmhu: "framer-v-t134mo" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0 ? void 0 : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Horizontal: "VeQSQ4PUT", Vertical: "yzW1wNmhu" };
var getProps = ({ height, id, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return { ...props, variant: (_ref = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref !== void 0 ? _ref : "yzW1wNmhu" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "yzW1wNmhu", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-t134mo", className, classNames), "data-framer-name": "Vertical", layoutDependency, layoutId: "yzW1wNmhu", ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, ...addPropertyOverrides({ VeQSQ4PUT: { "data-framer-name": "Horizontal" } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(Image, { background: { alt: "", fit: "fill", loading: getLoadingLazyAtYPosition(((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0) + (0 + (((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.height) || 42) - 0 - 40) / 2)), pixelHeight: 164, pixelWidth: 160, src: "https://framerusercontent.com/images/fgs2fO0j3a60aACvc1MEXuKtfFw.png" }, className: "framer-717x90", "data-framer-name": "Icon", layoutDependency, layoutId: "PNlP8iPBJ", style: { rotate: 0 }, variants: { VeQSQ4PUT: { rotate: 90 } } }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-9SXsl.framer-hejmk4, .framer-9SXsl .framer-hejmk4 { display: block; }", ".framer-9SXsl.framer-t134mo { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 42px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 40px; }", ".framer-9SXsl .framer-717x90 { flex: none; height: 40px; overflow: visible; position: relative; width: 40px; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-9SXsl.framer-t134mo { gap: 0px; } .framer-9SXsl.framer-t134mo > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-9SXsl.framer-t134mo > :first-child { margin-left: 0px; } .framer-9SXsl.framer-t134mo > :last-child { margin-right: 0px; } }"];
var FramerTf4Piv1dS = withCSS(Component, css, "framer-9SXsl");
var stdin_default = FramerTf4Piv1dS;
FramerTf4Piv1dS.displayName = "Helper/Patch";
FramerTf4Piv1dS.defaultProps = { height: 42, width: 40 };
addPropertyControls(FramerTf4Piv1dS, { variant: { options: ["yzW1wNmhu", "VeQSQ4PUT"], optionTitles: ["Vertical", "Horizontal"], title: "Variant", type: ControlType.Enum } });
addFonts(FramerTf4Piv1dS, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:helper/patch
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "VeQSQ4PUT"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
