// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";
import {
  className,
  css,
  fonts
} from "../chunks/chunk-JGN4MOVG.js";
import {
  Icon
} from "../chunks/chunk-IXDMRUES.js";
import "../chunks/chunk-BVM6H744.js";

// virtual:helper/tag
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Helper-Tag-kGaR.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ComponentViewportProvider, ControlType, cx, getFonts, getFontsFromSharedStyle, getPropertyControls, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var PhosphorFonts = getFonts(Icon);
var PhosphorControls = getPropertyControls(Icon);
var serializationHash = "framer-PBbng";
var variantClassNames = { TUIPQSIeZ: "framer-v-d61g4f" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableEnumMap = { Bold: "bold", Duotone: "duotone", Fill: "fill", Light: "light", Regular: "regular", Thin: "thin" };
var getProps = ({ height, icon, iconColor, id, title, weight, width, ...props }) => {
  var _humanReadableEnumMap_weight, _ref, _ref1, _ref2, _ref3, _ref4;
  return { ...props, fPdfDrTRv: (_ref1 = (_ref = (_humanReadableEnumMap_weight = humanReadableEnumMap[weight]) !== null && _humanReadableEnumMap_weight !== void 0 ? _humanReadableEnumMap_weight : weight) !== null && _ref !== void 0 ? _ref : props.fPdfDrTRv) !== null && _ref1 !== void 0 ? _ref1 : "fill", hxelCmDBG: (_ref2 = title !== null && title !== void 0 ? title : props.hxelCmDBG) !== null && _ref2 !== void 0 ? _ref2 : "Benefits", nkyMT5Gn4: (_ref3 = iconColor !== null && iconColor !== void 0 ? iconColor : props.nkyMT5Gn4) !== null && _ref3 !== void 0 ? _ref3 : "rgb(201, 128, 79)", UxnZrSyH8: (_ref4 = icon !== null && icon !== void 0 ? icon : props.UxnZrSyH8) !== null && _ref4 !== void 0 ? _ref4 : "Star" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className: className2, layoutId, variant, UxnZrSyH8, nkyMT5Gn4, fPdfDrTRv, hxelCmDBG, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "TUIPQSIeZ", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [className];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsxs(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-d61g4f", className2, classNames), "data-framer-name": "Tag", layoutDependency, layoutId: "TUIPQSIeZ", ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, children: [/* @__PURE__ */ _jsx(ComponentViewportProvider, { children: /* @__PURE__ */ _jsx(motion.div, { className: "framer-4k92sv-container", layoutDependency, layoutId: "KaYDYmPDl-container", children: /* @__PURE__ */ _jsx(Icon, { color: nkyMT5Gn4, height: "100%", iconSearch: "House", iconSelection: UxnZrSyH8, id: "KaYDYmPDl", layoutId: "KaYDYmPDl", mirrored: false, selectByList: true, style: { height: "100%", width: "100%" }, weight: fPdfDrTRv, width: "100%" }) }) }), /* @__PURE__ */ _jsx(RichText, { __fromCanvasComponent: true, children: /* @__PURE__ */ _jsx(React.Fragment, { children: /* @__PURE__ */ _jsx(motion.p, { className: "framer-styles-preset-jycf3n", "data-styles-preset": "QPTmydKPK", children: "Benefits" }) }), className: "framer-1b2b1yy", "data-framer-name": "Text", fonts: ["Inter"], layoutDependency, layoutId: "B43ci5_iI", style: { "--framer-paragraph-spacing": "0px" }, text: hxelCmDBG, verticalAlignment: "top", withExternalLayout: true })] }) }) }) });
});
var css2 = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-PBbng.framer-b0o5o7, .framer-PBbng .framer-b0o5o7 { display: block; }", ".framer-PBbng.framer-d61g4f { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-PBbng .framer-4k92sv-container { flex: none; height: 22px; position: relative; width: 22px; }", ".framer-PBbng .framer-1b2b1yy { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-PBbng.framer-d61g4f { gap: 0px; } .framer-PBbng.framer-d61g4f > * { margin: 0px; margin-left: calc(6px / 2); margin-right: calc(6px / 2); } .framer-PBbng.framer-d61g4f > :first-child { margin-left: 0px; } .framer-PBbng.framer-d61g4f > :last-child { margin-right: 0px; } }", ...css];
var Framerd1chySEt1 = withCSS(Component, css2, "framer-PBbng");
var stdin_default = Framerd1chySEt1;
Framerd1chySEt1.displayName = "Helper/Tag";
Framerd1chySEt1.defaultProps = { height: 27, width: 93 };
addPropertyControls(Framerd1chySEt1, { UxnZrSyH8: (PhosphorControls === null || PhosphorControls === void 0 ? void 0 : PhosphorControls["iconSelection"]) && { ...PhosphorControls["iconSelection"], defaultValue: "Star", description: void 0, hidden: void 0, title: "Icon" }, nkyMT5Gn4: { defaultValue: "rgb(201, 128, 79)", title: "Icon Color", type: ControlType.Color }, fPdfDrTRv: (PhosphorControls === null || PhosphorControls === void 0 ? void 0 : PhosphorControls["weight"]) && { ...PhosphorControls["weight"], defaultValue: "fill", description: void 0, hidden: void 0, title: "Weight" }, hxelCmDBG: { defaultValue: "Benefits", displayTextArea: false, title: "Title", type: ControlType.String } });
addFonts(Framerd1chySEt1, [{ explicitInter: true, fonts: [{ family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400" }, { family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400" }] }, ...PhosphorFonts, ...getFontsFromSharedStyle(fonts)], { supportsExplicitInterCodegen: true });

// virtual:helper/tag
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
