// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 61763921e49c2823 "Suprema (copy)", do not edit manually */
"use client";

// virtual:progress-line
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framer.com/m/Progress-Line-r4BQ.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["fH1I3QpJ5", "L2eRSjkGH", "Cv4ZkZ5h7"];
var serializationHash = "framer-zpoDo";
var variantClassNames = { Cv4ZkZ5h7: "framer-v-sq9xsm", fH1I3QpJ5: "framer-v-1c1vx4e", L2eRSjkGH: "framer-v-o0op2r" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0 ? void 0 : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { delay: 0, duration: 0.4, ease: [0, 0, 1, 1], type: "tween" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Big: "Cv4ZkZ5h7", Medium: "L2eRSjkGH", Small: "fH1I3QpJ5" };
var getProps = ({ height, id, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return { ...props, variant: (_ref = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref !== void 0 ? _ref : "fH1I3QpJ5" };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "fH1I3QpJ5", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-1c1vx4e", className, classNames), "data-framer-name": "Small", layoutDependency, layoutId: "fH1I3QpJ5", ref: ref !== null && ref !== void 0 ? ref : ref1, style: { backgroundColor: "var(--token-c40dec17-ad9b-478b-a7f0-e25384b15814, rgb(255, 255, 255))", ...style }, ...addPropertyOverrides({ Cv4ZkZ5h7: { "data-framer-name": "Big" }, L2eRSjkGH: { "data-framer-name": "Medium" } }, baseVariant, gestureVariant) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-zpoDo.framer-e5nrh0, .framer-zpoDo .framer-e5nrh0 { display: block; }", ".framer-zpoDo.framer-1c1vx4e { height: 2px; overflow: hidden; position: relative; width: 2px; }", ".framer-zpoDo.framer-v-o0op2r.framer-1c1vx4e { height: 150px; }", ".framer-zpoDo.framer-v-sq9xsm.framer-1c1vx4e { height: 500px; }"];
var FramerROezNhj5a = withCSS(Component, css, "framer-zpoDo");
var stdin_default = FramerROezNhj5a;
FramerROezNhj5a.displayName = "Progress Line";
FramerROezNhj5a.defaultProps = { height: 2, width: 2 };
addPropertyControls(FramerROezNhj5a, { variant: { options: ["fH1I3QpJ5", "L2eRSjkGH", "Cv4ZkZ5h7"], optionTitles: ["Small", "Medium", "Big"], title: "Variant", type: ControlType.Enum } });
addFonts(FramerROezNhj5a, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:progress-line
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "fH1I3QpJ5"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "HXXIFJoEl": { "path": "/blog/case-u1" }, "KDtxaRgl5": { "path": "/ileti\u015Fim" }, "MxwjFQVGH": { "path": "/blog/case-brewmood" }, "Rtav_h6QE": { "path": "/blog/case-corendon" }, "SubI5NfBy": { "path": "/waitlist" }, "YSEeQzjwr": { "path": "/blog" }, "augiA20Il": { "path": "/" }, "cQ6Vb7aXD": { "path": "/404" }, "gM0eTBspA": { "path": "/hakk\u0131nda" }, "l0j3rKbnl": { "path": "/kvkk" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "HXXIFJoEl": {
          "path": "/blog/case-u1"
        },
        "KDtxaRgl5": {
          "path": "/ileti\u015Fim"
        },
        "MxwjFQVGH": {
          "path": "/blog/case-brewmood"
        },
        "Rtav_h6QE": {
          "path": "/blog/case-corendon"
        },
        "SubI5NfBy": {
          "path": "/waitlist"
        },
        "YSEeQzjwr": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        },
        "cQ6Vb7aXD": {
          "path": "/404"
        },
        "gM0eTBspA": {
          "path": "/hakk\u0131nda"
        },
        "l0j3rKbnl": {
          "path": "/kvkk"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "61763921e49c2823532f999af0521758dc030056f0ee1d5ff07995fe62f9a2ed",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
